### ISSUE TITLE
After cloning and running the project cannot open the work in browser to debug

### ISSUE THREAD

**Issue by TheSenPie** [eXponenta/pixi5-playables-boilerplate#12]
Hi,

I just cloned the repo in my local, did npm install, and then run gulp command from cmd. The server started with this log: 

```
C:\Users\user\js\pixi5-playables-boilerplate>gulp
[17:43:02] Using gulpfile ~\Documents\projects\js\pixi5-playables-boilerplate\gulpfile.js
[17:43:02] Starting 'default'...
[17:43:02] Starting server...
[17:43:02] ==Watch==
[17:43:02] Dev app started http://localhost:8080
[17:43:02] LiveReload started on port 35729
[17:43:02] Running server
```

Then when I visited http://localhost:8080/templates/debug/index.html to see the live version of the project I get this errors. 

![image png a47cfffd062d7863e4da34ef168ed337](https://user-images.githubusercontent.com/20699484/123546620-68d38880-d76e-11eb-8f50-96146e45452b.png)

How can I overcome this error? or maybe I opened the wrong file. I will appreciate it if you include some kind of Readme.md in the repo for beginners to right away start their projects and do not get stuck on this type of issue. Let me know if you need any additional info. Btw, here is the full screenshot.
If you want to contact me here is my discord username for quick response: "SenPie#1915"

![image png fcb7a262dc0ad8b5b21f9e4e6ae3baf2](https://user-images.githubusercontent.com/20699484/123546719-d1226a00-d76e-11eb-8fb8-b8d2f97cabaf.png)

**Comment by eXponenta** [comment]
You should load debug bundle from "dist-dev" instead of templates, templates is ... templates, it used only for pre-processing 

https://github.com/eXponenta/pixi5-playables-boilerplate/blob/master/gulpfile.js#L102

**Comment by TheSenPie** [comment]
> 
> 
> You should load debug bundle from "dist-dev" instead of templates, templates is ... templates, it used only for pre-processing
> 
> https://github.com/eXponenta/pixi5-playables-boilerplate/blob/master/gulpfile.js#L102

"dist-dev" does not work work either, and I get this error during loading 
```Uncaught (in promise) Sheet can't be undefined```
![image](https://user-images.githubusercontent.com/20699484/123548325-6294da80-d775-11eb-885f-9f486af29dde.png)

**Comment by eXponenta** [comment]
All is ok.
Error said that spritesheet wasn't found.
Why?
You should debug this itself, because this is resources loading trouble.
Boilerplate was developed for specific pixi and tiled version, there are not guaranteed that it still works without modification.

Then I remove original resources.

**Comment by TheSenPie** [comment]
Why would you remove original resources without removing references to them? It puts newbies into even more confusion. Could you please add resources back, so I can see what will be the final result, because right now I am only guessing.  After refreshing the page I got even more errors, however I did not touch the code.
![image](https://user-images.githubusercontent.com/20699484/123552796-d7bddb00-d788-11eb-88d7-82cc8df4bb42.png)

**Comment by TheSenPie** [comment]
When you made the boilerplate it was working right? Please push it in that working state, I will remove the unnecesary assets manually.

**Comment by eXponenta** [comment]
I willn't do this.
I removed original resources because it hasn't public usage licence.

You shouldn't use this if you cannot.

Your choice.

Technical this is internal project, and should be used only for devs that has some experience.

**Comment by TheSenPie** [comment]
ну окей
